import type { Metadata } from "next";
import { headers } from 'next/headers'
import "./globals.css";
import {Providers} from '@/context'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
          <Providers cookie={headers().get('cookie') ?? ''}>
            {children}
          </Providers>
      </body>
    </html>
  );
}

