/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as pair from "./pair";
export type { pair };
import type * as router from "./router";
export type { router };
