/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dex from "./dex";
export type { dex };
export type { MintableToken } from "./MintableToken";
